import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const nunati = Nunito({
  variable: "--font-nunati",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body className={nunati.className}>{children}</body>
      </html>
    </TRPCReactProvider>
  );
}
