version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pg-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tagxi
      POSTGRES_PASSWORD: tagxi
      POSTGRES_DB: tagxi
